services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=notification_center'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=1'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
