spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/notification_center
    password: ''
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: none
  email:
    host: ''
    port: ''
    username: ''
    password: ''

